name: Main

on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GO_VERSION: ^1.21

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run tests
      run: go test -v ./...

  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Configure environment
      id: context
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Release
      uses: goreleaser/goreleaser-action@v3
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to registry
      run: |
        docker login \
          -u ${{ github.actor }} \
          -p ${{ secrets.GITHUB_TOKEN }} \
          ${{ env.REGISTRY }}

    - name: Build image
      uses: linecard/nixless@main
      with:
        registry: ${{ env.REGISTRY }}/linecard
        image: ${{ env.IMAGE_NAME }}
        tag: ${{ steps.context.outputs.tag }}
